### ISSUE TITLE
Use of dated Ubuntu Xenial base image

### ISSUE THREAD

**Issue by jmpolom** [thehomerepot/ivideon#7]
The ivideon server Dockerfile uses a rather dated Ubuntu Xenial (16.04) base image despite newer LTS releases being available. Although 16.04 will be supported by Canonical until 2024, I'm wondering why the container hasn't been migrated to a newer image. What is the rationale for this?

I haven't run the ivideon server myself yet so I'm wondering if perhaps their stated distro support is not quite as simple as stated. They claim to support Debian 8 and 9 but not 10 so is it a case of the package having some dated dependencies?

**Comment by thehomerepot** [comment]
I don't use this container personally so I simply used the latest LTS release of Ubuntu they listed as supported.
https://www.ivideon.com/help/software/ivideon-server/can-ivideon-server-be-installed-on-my-os/
